### ISSUE TITLE
How to use multiple inputs(keys)?

### ISSUE THREAD

**Issue by FKLC** [ofek/bit#26]
How to use multiple inputs like that: https://blockchain.info/tx/40886a2d39682ba9111ea6d0dc4764660ef1cc212462d858b51fdc39f7879883

**Comment by teran-mckinney** [comment]
You can't at all. The code is structured around the key as being the lowest common denominator and not the transaction.

You'd have to rewrite quite a bit. Maybe there is a clean way to implement it, but I'm not positive. Feel free to submit a pull request.

(@ofek or @bjarnemagnussen, feel free to correct me if I'm wrong.)

**Comment by FKLC** [comment]
@teran-mckinney btw if I would use multiple inputs does Am I pay same fee or Am I need to be pay per input.
I mean I want to being anonymized using different addresses per transactions. And after all I want to merge all my coins without paying fee are there any way of it?

**Comment by teran-mckinney** [comment]
Fees are per transaction. Sum of inputs minus sum of outputs is the fee.

Using different addresses per transaction is not anonymization. Maybe you can "mix your own coins", but I think using a real mixer (or two) is better.

You can't merge your coins without paying a fee unless you have a nice miner and zero transactions in mempool. If anything, more complicated transactions require higher fees. Fees are more often looked at as fee per byte.

Now, if you send from 10 wallets into 1 wallet (in a single transaction) you will pay less TX fees up front and when you want to spend from that wallet since it'll be a single output vs multiple. So there is value in what you want to do.

**Comment by ofek** [comment]
https://ofek.github.io/bit/guide/transactions.html#unspent-consolidation

**Comment by ofek** [comment]
As @teran-mckinney said, Bit does not yet support P2SH.
