### ISSUE TITLE
How to specify exact fee and send all the bitcoins to another address?

### ISSUE THREAD

**Issue by kigawas** [ofek/bit#5]
Thanks for developing this amazing project.

I have 8250 satoshis on Testnet, and when I invoke key.send() and specify the fee, it raised an error, because the fee parameter is satoshis/byte, not just fee itself.

How can I specify the fee and send all the bitcoins to another address?

**Comment by ofek** [comment]
Hi there! If you are on testnet, you can safely do `fee=0`.

Bit doesn't support providing a flat fee because transactions can be all different sizes. As such, it is highly likely your transaction would be rejected by the network if the fee is off even a little.

Bit does provide an easy way to send entire balance: https://ofek.github.io/bit/guide/transactions.html#transfer-funds

**Comment by ofek** [comment]
@kigawas Does that answer your question?

**Comment by kigawas** [comment]
Thank you for your help!
