### ISSUE TITLE
question about P2WPKH

### ISSUE THREAD

**Issue by su314ka** [ofek/bit#95]
Hello,

It`s possible to create BECH32 (P2WPKH) addresses with bit library?
Thanks!

**Comment by bjarnemagnussen** [comment]
Hi,

At the moment unfortunately not. The changes needed to generate Bech32 addresses are relatively simple. It is however not implemented because some of the WebAPIs that Bit uses do not support Bech32.

Adding more APIs that support Bech32 and then being able to distinguish them by the different features they support is being proposed in a PR.

Thereafter it would be fairly easy to add Bech32 addresses to Bit.
